// Released under the MIT License.
// Copyright, 2026, by Samuel Williams.

// Generated by `cargo bake --regenerate`; do not edit.
use bake_cargo as _;
use bake_test_rust as _;
use socketry_project as _;
